### ISSUE TITLE
Submission problem http status 400

### ISSUE THREAD

**Issue by jonmaiga** [loda-lang/loda-cpp#56] opened 2021-11-13 08:44 UTC
```
2021-11-13 09:31:25|ALERT|First program for A142938: Primes congruent to 29 mod 64. Terms: 29,157,349,541,733,797,1117,1181,1373,1693. Submitted by Jon Maiga
2021-11-13 09:31:25|ALERT|Faster program for A137421: Decimal expansion of growth constant in random Fibonacci sequence. Terms: 1,2,0,5,5,6,9,4,3,0. Submitted by Jon Maiga
curl: (22) The requested URL returned error: 400 Bad Request
2021-11-13 09:31:26|ERROR|Error submitting program to miner API
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error submitting program to miner API
2021-11-13 09:31:29|INFO |Generated 2614001 programs
```

Looks like the miner (binary) sent a bad request and was terminated.

**Comment by ckrause** [comment] 2021-11-13 14:27
Might be caused by a race condition in `ApiClient::postProgram()`. Needs a bug fix.

**Comment by ckrause** [comment] 2021-11-14 11:32
should be fixed in new version

**Closed by ckrause** 2021-11-14 11:32 UTC
Labels: bug
